#!/bin/bash
set -e
#Script to download all my github repositories
#TODO
   # Create a nice documentation for users 
   
DIR=~/home/liopin

check_dir(){
if [ -d "$DIR" ];then
  cd $DIR
else
  printf "%s directory does not exist.\n" $DIR
  printf "Creating %s...\n" $DIR
	mkdir -p $DIR
  cd $DIR
fi
}

download_repos_by_language(){
  for i in $(gh repo list --source --language "$1" | awk '{print $1}');do
    gh repo clone "$i"
  done
}

download_all_repos(){
  for i in $(gh repo list | awk '{print $1}'); do
    gh repo clone "$i"
  done
}

download_one_repo(){
  gh repo clone "$1"
}

install_gh(){
	read -p "Do you want to download github cli [Yy]: " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]];then
	  apt update
	  apt install gh	
  fi
}

if ! [ -x "$(command -v gh)" ]; then
  printf "Error: github CLI is not installed.\n" >&2
  install_gh
  check_prequisites
fi

while getopts 's:l:a' OPTION; do
  case "$OPTION" in
    s)
      check_dir
      download_one_repo "$OPTARG"
      ;;
    l)
      check_dir
      download_repos_by_language "$OPTARG"
      ;;
    a)
      check_dir
      download_all_repos
      ;;
    *)
      echo "This is a unvalide options"
      ;;
  esac
done
shift "$(($OPTIND -1))"
